<a href="https://colab.research.google.com/github/NafisFuadTanvir/Data-mining-works/blob/main/DataMiningLabreport(1)work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


data=pd.read_csv("/content/Twitter Stock Market Dataset.csv")

In [ ]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-11-07,45.099998,50.090000,44.000000,44.900002,44.900002,117701670.0
1,2013-11-08,45.930000,46.939999,40.685001,41.650002,41.650002,27925307.0
2,2013-11-11,40.500000,43.000000,39.400002,42.900002,42.900002,16113941.0
3,2013-11-12,43.660000,43.779999,41.830002,41.900002,41.900002,6316755.0
4,2013-11-13,41.029999,42.869999,40.759998,42.599998,42.599998,8688325.0
...,...,...,...,...,...,...,...
2259,2022-10-28,NaN,NaN,NaN,NaN,NaN,NaN
2260,2022-10-31,NaN,NaN,NaN,NaN,NaN,NaN
2261,2022-11-01,NaN,NaN,NaN,NaN,NaN,NaN
2262,2022-11-02,NaN,NaN,NaN,NaN,NaN,NaN
2263,2022-11-03,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#checking the data infos

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2264 entries, 0 to 2263
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2264 non-null   object
 1   Open       2259 non-null   float64
 2   High       2259 non-null   float64
 3   Low        2259 non-null   float64
 4   Close      2259 non-null   float64
 5   Adj Close  2259 non-null   float64
 6   Volume     2259 non-null   float64
dtypes: float64(6), object(1)
memory usage: 123.9+ KB

In [ ]:
data.drop("Low",axis=1,inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2264 entries, 0 to 2263
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2264 non-null   object
 1   Open       2259 non-null   float64
 2   High       2259 non-null   float64
 3   Close      2259 non-null   float64
 4   Adj Close  2259 non-null   float64
 5   Volume     2259 non-null   float64
dtypes: float64(5), object(1)
memory usage: 106.2+ KB

In [ ]:
updated_data = data
updated_data["High"]=updated_data["High"].fillna(updated_data["High"].mean())

In [ ]:
 updated_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2264 entries, 0 to 2263
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2264 non-null   object
 1   Open       2259 non-null   float64
 2   High       2264 non-null   float64
 3   Close      2259 non-null   float64
 4   Adj Close  2259 non-null   float64
 5   Volume     2259 non-null   float64
dtypes: float64(5), object(1)
memory usage: 106.2+ KB

In [ ]:
colomn_deletedata= updated_data.dropna(axis=1)
updated_data

            Date       Open       High      Close  Adj Close       Volume
0     2013-11-07  45.099998  50.090000  44.900002  44.900002  117701670.0
1     2013-11-08  45.930000  46.939999  41.650002  41.650002   27925307.0
2     2013-11-11  40.500000  43.000000  42.900002  42.900002   16113941.0
3     2013-11-12  43.660000  43.779999  41.900002  41.900002    6316755.0
4     2013-11-13  41.029999  42.869999  42.599998  42.599998    8688325.0
...          ...        ...        ...        ...        ...          ...
2259  2022-10-28        NaN  36.699881        NaN        NaN          NaN
2260  2022-10-31        NaN  36.699881        NaN        NaN          NaN
2261  2022-11-01        NaN  36.699881        NaN        NaN          NaN
2262  2022-11-02        NaN  36.699881        NaN        NaN          NaN
2263  2022-11-03        NaN  36.699881        NaN        NaN          NaN

[2264 rows x 6 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
updated_data["Volume"]=label_encoder.fit_transform(updated_data["Volume"])

In [ ]:
updated_data["Volume"].unique()

array([2241, 1853, 1041, ..., 1858, 2248, 2258])